name: .NET Core

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-20.04

    env:
      COMMIT_REF: $(git rev-parse --short "$GITHUB_SHA")

    steps:
      - uses: actions/checkout@v2

      - name: Run Bicep build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: Infrastructure/main.bicep

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: azure/arm-deploy@v1
        id: deploy
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: demoaspnet5aci-rg
          template: ./Infrastructure/main.json
          deploymentMode: Incremental

      - name: Build image with ACR
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az acr build --registry ${{ steps.deploy.outputs.registryNameOutput }} --image aspnet5webapp:${{ env.COMMIT_REF }} ./WebApp/

      - name: Deploy the image to Azure Container Instance
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az container create -g ${{ steps.deploy.outputs.resourceGroupOutput }} -n ${{ steps.deploy.outputs.webAppNameOutput }} --image ${{ steps.deploy.outputs.registryLoginServer }}/aspnet5webapp:${{ env.COMMIT_REF }} --cpu 1 --memory 1 --registry-username ${{ steps.deploy.outputs.registryNameOutput }} --registry-password ${{ steps.deploy.outputs.registryPasswordOutput }}
